---
title: "Web-based Tasks"
author: "Julie M. Schneider"
date: "`r format(Sys.Date())`"
output:
   html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    css: style.css
---

```{r setup, include=FALSE, cache=F}
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/', echo=TRUE, tidy=TRUE, message=F, warning=F, cache=T)
```

## Library Import
```{r,include=FALSE,echo=FALSE,warning=FALSE}
#Loading library
 library(tidyr); library(dplyr)
```

```{r}
setwd("/Volumes/data/projects/sllip/data/web-based/quil_task/")
quil_files <- list.files(pattern="data_*")

file.list <- list.files(path="/Volumes/data/projects/sllip/data/web-based/quil_task/",pattern="data*", full.names = TRUE)
#asl_df = read.csv("asl_task/asl_n10.csv")
#quil_df <- read.csv("quil_task/quil_n10.csv")
```

```{r}
#initiate dataframe
quils_df <- NULL
# Extract relevant data and combine it
for (file in file.list) {
##Select only the relevant columns
  extracted_data <-
    read.csv(file)[c("Event.Index", "Participant.Private.ID", "Trial.Number", "Reaction.Time", "Attempt","Correct","Incorrect")]
  quils_df <- rbind(quils_df, extracted_data)
}
```

```{r}
clean_quil <- data.frame(quils_df$Participant.Private.ID)
clean_quil$accuracy <- quils_df$Correct[quils_df$Attempt==1]
clean_quil<-clean_quil[complete.cases(clean_quil), ]

clean_quil$quils_df.Participant.Private.ID <- as.numeric(clean_quil$quils_df.Participant.Private.ID)
clean_quil$accuracy <- as.numeric(clean_quil$accuracy)

quil_accuracy <- clean_quil %>%
  group_by(quils_df.Participant.Private.ID) %>%
  summarise(quil_accuracy = mean(accuracy, na.rm = TRUE))

names(quil_accuracy)[1] <- "Gorilla.privateID"
subject_list<- read.csv("/Volumes/data/projects/sllip/data/web-based/quil_task/quil_decoder.csv")
quil_accuracy<-merge(subject_list,quil_accuracy, by="Gorilla.privateID")

write.csv(quil_accuracy,"/Volumes/data/projects/sllip/data/web-based/quil_task/quil_accuracy.csv")
```

```{r}
res <- t.test(quil_accuracy$quil_accuracy, mu = .25)
res
```

```{r}
setwd("/Volumes/data/projects/sllip/data/web-based/asl_task/")
asl_files <- list.files(pattern="data_*")

asl.file.list <- list.files(path="/Volumes/data/projects/sllip/data/web-based/asl_task/",pattern="data*", full.names = TRUE)

```

```{r}
#initiate dataframe
asl_df <- NULL
# Extract relevant data and combine it
for (file in asl.file.list) {
##Select only the relevant columns
  asl_extracted_data <-
    read.csv(file)[c("Event.Index", "Participant.Private.ID", "Trial.Number", "Reaction.Time", "Attempt","Correct","Incorrect")]
  asl_df <- rbind(asl_df, asl_extracted_data)
}

```

```{r}
clean_asl <- data.frame(asl_df$Participant.Private.ID)
clean_asl$accuracy <- asl_df$Correct[asl_df$Attempt==1]
clean_asl<-clean_asl[complete.cases(clean_asl), ]
asl_accuracy<-aggregate(clean_asl[, "accuracy"], list(clean_asl$asl_df.Participant.Private.ID), mean)
```


```{r}
res <- t.test(asl_accuracy$x, mu = .50)
res
```



